import type { Metadata } from "next";
import Account from "./Providers";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Account>{children}</Account>
      </body>
    </html>
  );
}
